baseURL = 'https://phoebeivy.dev/'
languageCode = 'en-us'
title = 'phoebe'
enableEmoji = true
enableRobotsTXT = true

[params]
  description = "trans girl making little projects"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true