baseURL = 'https://phoebeivy.dev/'
languageCode = 'en-us'
title = 'phoebe'
enableEmoji = true
enableRobotsTXT = true

[params]
  description = "trans girl making little projects"
  images = [ "favicon.png" ]

[social]
  twitter = "cutewitchphoebe"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80
[[related.indices]]
  name = 'date'
  weight = 10